/**
 * Generates a README.md with project overview.
 */
export function generateReadme(ir) {
  let md = `# Blueprint Project\n\nGenerated by [Blueprint](https://blueprint.appwrite.io) — Visual Appwrite System Designer.\n\n## Services\n\n`;

  if (ir.auth) {
    md += `- **Auth** — Providers: ${ir.auth.providers.join(", ")}\n`;
  }
  if (ir.database) {
    md += `- **Database** — ${ir.database.collections.length} collection(s): ${ir.database.collections.map((c) => c.name).join(", ")}\n`;
  }
  if (ir.storage) {
    md += `- **Storage** — ${ir.storage.buckets.length} bucket(s): ${ir.storage.buckets.map((b) => b.name).join(", ")}\n`;
  }
  if (ir.functions.length > 0) {
    md += `- **Functions** — ${ir.functions.length} function(s): ${ir.functions.map((f) => f.name).join(", ")}\n`;
  }
  if (ir.realtime) {
    md += `- **Realtime** — Subscriptions enabled\n`;
  }
  if (ir.messaging) {
    md += `- **Messaging** — Channels: ${ir.messaging.channels.join(", ") || "none configured"}\n`;
  }

  md += `\n## Setup\n\n`;
  md += `1. Copy \`.env.example\` to \`.env\` and fill in your Appwrite credentials\n`;
  md += `2. Run \`npm install\`\n`;

  if (ir.database) {
    md += `3. Run \`npx tsx scripts/setup-collections.ts\` to create collections\n`;
  }
  if (ir.storage) {
    md += `${ir.database ? "4" : "3"}. Run \`npx tsx scripts/setup-storage.ts\` to create buckets\n`;
  }

  md += `\n## Development\n\n\`\`\`bash\nnpm run dev\n\`\`\`\n`;

  md += `\n## Project Structure\n\n\`\`\`\n`;
  md += `src/\n`;
  md += `  lib/appwrite.ts     — Appwrite client setup\n`;
  if (ir.auth) md += `  lib/auth.ts         — Auth helpers & hooks\n`;
  if (ir.database) {
    md += `  hooks/              — CRUD hooks per collection\n`;
    md += `  types/              — TypeScript types per collection\n`;
    md += `  schemas/            — Zod validation schemas\n`;
  }
  if (ir.storage) md += `  hooks/useStorage.ts — File upload/download hook\n`;
  if (ir.functions.length > 0) md += `functions/            — Serverless function scaffolds\n`;
  md += `scripts/              — Setup scripts (run once)\n`;
  md += `\`\`\`\n`;

  return [
    {
      path: "README.md",
      content: md,
      language: "markdown",
    },
  ];
}
